services:
  vllm-qwen3-30b:
    image: vllm/vllm-openai:latest
    container_name: vllm-Qwen3-30B-A3B-GPTQ-Int4
    runtime: nvidia
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "9002:9002"
    networks:
      - webui-net
    ipc: host
    command: |
      --model Qwen/Qwen3-30B-A3B-GPTQ-Int4
      --gpu-memory-utilization 0.75
      --host 0.0.0.0
      --port 9002
      --max-num-seqs 128
      --max-num-batched-tokens 1024
      --max-model-len 32768
      --async-scheduling
      --api-key 123456
      --reasoning-parser qwen3
      --enable-auto-tool-choice
      --tool-call-parser hermes
      --generation-config auto
      --override-generation-config '{"temperature":0.6,"top_p":0.95,"top_k":20,"presence_penalty":1.5,"chat_template_kwargs":{"enable_thinking":true}}'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
networks:
  webui-net:
    external: true